# Generated by Django 4.2.19 on 2025-03-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_payment_booking_alter_transaction_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='lead_user',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
